### ISSUE TITLE
Update donut chart vizualisation

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/geowahl-api#12]
### Todos
- [x] Remove JSON output
- [x] Add parties color
- [x] Set appropiate font color ( how about `white` )
- [x] Make font bigger ( how about `1em` )
- [x] Make responsive
