### ISSUE TITLE
Finish documenting web services

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/geowahl-api#13]
## Todos
- [x] Revise docs
- [x] Add missing JSON result props for `/{electionSlug}/{stateSlug}/{districtId}`
- [x] Fix typo in JSON result main prop `districts` in `/{electionSlug}/{stateSlug}/{districtId}` and `/{electionSlug}/{latitude},{longitude}`
- [ ] Fix README.md incorrect links
- [ ] Document `/{electionSlug}/{stateSlug}/donut-chart` **( waiting for #12 )**
- [ ] Document `/{electionSlug}/{stateSlug}/{districtId}/donut-chart` **( waiting for #12 )**
- [ ] Document error responses **( waiting for #14 )**
